# This makefile compiles needed files for WK9 final

final:
	g++ -g main.cpp Menu.cpp Barbarian.cpp BlueMan.cpp Creature.cpp Dice.cpp Game.cpp Goblin.cpp Reptile.cpp Shadow.cpp Map.cpp Room.cpp RoomOne.cpp RoomTwo.cpp RoomThree.cpp RoomFour.cpp RoomFive.cpp Player.cpp Weapons.cpp RiotGear.cpp BattleAxe.cpp Shield.cpp Mace.cpp Sword.cpp -o final

clean: 
	rm -i final
