# This makefile compiles needed files for WK7 Assign4

Assign4:
	g++ -g main.cpp Menu.cpp Barbarian.cpp BlueMan.cpp Creature.cpp Dice.cpp Game.cpp Goblin.cpp Reptile.cpp Shadow.cpp Queue.cpp Stack.cpp -o Assign4

clean: 
	rm -i Assign4
