# This makefile compiles needed files for WK5 Assign3

Assign3:
	g++ -g main.cpp Menu.cpp Barbarian.cpp BlueMan.cpp Creature.cpp Dice.cpp Game.cpp Goblin.cpp Reptile.cpp Shadow.cpp  -o Assign3

clean: 
	rm -i Assign3
